server.port: 8761
spring:
  application.name: eureka-service
  profiles.active: ${SPRING_PROFILES_ACTIVE:dev}
  config.import: "configserver:http://localhost:8888"
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.discovery: TRACE
    com.netflix.eureka: TRACE
    org.springframework.web.client: TRACE
