gateway:
  property: Gateway Profile Dev
server:
  port: 7070
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: lb://todo-service
          predicates:
            - Path=/api/v1/todos/**
    loadbalancer:
      ribbon:
        enabled: false
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
