main:
  property: Gateway Profile Dev
server:
  port: 7070
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: main-service
      uri: lb://main-service
      predicates:
        - Path=/api/v1/**
    loadbalancer:
      ribbon:
        enabled: false
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
