gateway:
  property: Gateway Profile Prod
server:
  port: 7080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/api/v1/todo/**
    loadbalancer:
      ribbon:
        enabled: false
