gateway:
  property: Gateway Profile Dev
server:
  port: 7080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/api/v1/todo/**
        - id: todo-service
          uri: lb://todo-service
          predicates:
            - Path=/api/v1/todos/**
        - id: todo-service-actuator
          uri: lb://todo-service
          predicates:
            - Path=/actuator/**
    loadbalancer:
      ribbon:
        enabled: false
