main:
  property: Main Profile Prod
server:
  port: 0
spring:
  application:
    name: main-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}
