todo:
  property: ToDo Profile Dev
  test: Test Property
server:
  port: 0
spring:
  application:
    name: todo-service
  cloud:
    vault:
      application-name: todo-service
      host: ${VAULT_HOST}
      port: ${VAULT_PORT}
      authentication: token
      token: ${VAULT_TOKEN}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
