todo:
  property: ToDo Profile Prod
  test: Test Property
server:
  port: 0
spring:
  application:
    name: todo-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}
