server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EnriqueRS/todo-spring
          default-label: master
          search-paths: config-files
